Es features done
walkadaw/andersen-js-course pull request #1
Opened 2019-06-02 11:34 UTC by walkadaw

2019-06-04 07:29 UTC, volvachev requested changes

2019-06-04 07:29 UTC, volvachev commented on src/array-practice/task10.js
> +  for (let meetup of meetups) {
В этой задаче ты должен за использовать методы массива.

2019-06-04 07:29 UTC, volvachev commented on src/array-practice/task3.js
> +  arr.reverse().forEach(result);
reverse мутирует исходный массив, используй reverse на новом массиве.

2019-06-04 07:29 UTC, volvachev commented on src/array-practice/task5.js
> +      return console.log(result);
Ты должен возвращать не undefined от консоль лога, а результат итерации, тоесть сам result, а не вызывать console.log здесь.

2019-06-04 07:29 UTC, volvachev commented on src/array-practice/task9.js
> +  arr.forEach((element, index) => {
Замени на reduce.

2019-06-04 07:29 UTC, volvachev commented on src/es-features/task10.js
> +// NewB.defaultUser = () => new NewB('text', 0);
Воспользуйся static method в классе.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static

2019-06-04 07:29 UTC, volvachev commented on src/es-features/task4.js
> +  obj[`baz${foo()}`] = 'new filed';
Это можно задать прямо в объекте
```
const data = 'dynamic'
const obj = {
  [data]: 'text'
}
```

2019-06-04 12:14 UTC, volvachev requested changes

2019-06-04 12:14 UTC, volvachev commented on src/array-practice/task5.js
> +      const result = arrayGenerator.next();
```
      const {done, value} = arrayGenerator.next();
      return done ? 'Complete!' : value;
```

2019-06-06 10:31 UTC, walkadaw commented on src/array-practice/task10.js
> +  for (let meetup of meetups) {
переделал через reduce

2019-06-06 10:32 UTC, walkadaw commented on src/array-practice/task3.js
> +  arr.reverse().forEach(result);
Исправил

2019-06-06 10:32 UTC, walkadaw commented on src/array-practice/task5.js
> +      return console.log(result);
Исправил

2019-06-06 10:33 UTC, walkadaw commented on src/array-practice/task9.js
> +  arr.forEach((element, index) => {
Заменил

2019-06-06 10:33 UTC, walkadaw commented on src/es-features/task10.js
> +// NewB.defaultUser = () => new NewB('text', 0);
Исправил

2019-06-06 10:33 UTC, walkadaw commented on src/es-features/task4.js
> +  obj[`baz${foo()}`] = 'new filed';
Исправил

2019-06-06 10:34 UTC, walkadaw commented on src/array-practice/task5.js
> +      const result = arrayGenerator.next();
Исправил

2019-06-06 10:47 UTC, walkadaw commented
Все исправил

2019-06-08 11:33 UTC, merged